parameters:
    d_wietor_pmanager.tcpdf.class: DWietor\Bundle\PmanagerBundle\Controller\TCPDFController
    d_wietor_pmanager.pdftemplate.entity.class:   DWietor\Bundle\PmanagerBundle\Entity\PDFTemplate
    d_wietor_pmanager.pdftemplate.manager.class:       DWietor\Bundle\PmanagerBundle\Entity\Manager\PDFTemplateActivityManager
    d_wietor_pmanager.twig.pdftemplate_security_policy.class: Twig_Sandbox_SecurityPolicy
    d_wietor_pmanager.twig.extension.pdftemplate.class:    DWietor\Bundle\PmanagerBundle\Twig\PDFTemplateExtension
    
    # Providers    
    d_wietor_pmanager.pdftemplate.variable_provider.class: DWietor\Bundle\PmanagerBundle\Provider\VariablesProvider
    d_wietor_pmanager.pdftemplate.variable_provider.entity.class: DWietor\Bundle\PmanagerBundle\Provider\EntityVariablesProvider
    d_wietor_pmanager.pdftemplate.variable_provider.system.class: DWietor\Bundle\PmanagerBundle\Provider\SystemVariablesProvider
    d_wietor_pmanager.pdftemplate.variable_provider.user.class: DWietor\Bundle\PmanagerBundle\Provider\LoggedUserVariablesProvider
    
    # Cache keys
    d_wietor_pmanager.cache.available_in_template_key: 'd_wietor_pmanager.available_in_template_fields'

    # pdf template renderer, twig instance
    d_wietor_pmanager.pdftemplate_renderer.class: DWietor\Bundle\PmanagerBundle\Provider\PDFTemplateRenderer
    d_wietor_pmanager.producttemplate_renderer.class: DWietor\Bundle\PmanagerBundle\Provider\ProductTemplateRenderer
    d_wietor_pmanager.publication_renderer.class: DWietor\Bundle\PmanagerBundle\Provider\PublicationRenderer
    d_wietor_pmanager.twig._security_policy.class: Twig_Sandbox_SecurityPolicy

    #d_wietor_pmanager.helper.datagrid.pdftemplate.class:           DWietor\Bundle\PmanagerBundle\Datagrid\PDFTemplateGridHelper1
    #d_wietor_pmanager.datagrid_query_factory.class:           DWietor\Bundle\PmanagerBundle\Datagrid\PDFTemplateQueryFactory
    d_wietor_pmanager.pdftemplate.datagrid_view_list.class: DWietor\Bundle\PmanagerBundle\Datagrid\PDFTemplateViewList
    d_wietor_pmanager.pdftemplate.datagrid_helper.class:    DWietor\Bundle\PmanagerBundle\Datagrid\PDFTemplateGridHelper

    d_wietor_pmanager.pdftemplate.owner.provider.storage.class: DWietor\Bundle\PmanagerBundle\Entity\Provider\PDFTempalteOwnerProviderStorage
    d_wietor_pmanager.pdftemplate.api.class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
    d_wietor_pmanager.activity_list.provider.class:       DWietor\Bundle\PmanagerBundle\Provider\PmanagerActivityListProvider
    d_wietor_pmanager.placeholder.filter.class:            DWietor\Bundle\PmanagerBundle\Placeholder\PlaceholderFilter  
    # Config provider
    d_wietor_pmanager.provider.configuration.class:         DWietor\Bundle\PmanagerBundle\Provider\ConfigurationProvider  
    oro_email.provider.email_recipients.helper.class: DWietor\Bundle\PmanagerBundle\Provider\EmailRecipientsHelper

services: 
#    d_wietor_pmanager.example:
#        class: %d_wietor_pmanager.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
         # Form Types
    d_wietor_pmanager.provider.configuration:
        class: %d_wietor_pmanager.provider.configuration.class%
        arguments:
            - @oro_config.global
            - '@oro_entity.doctrine_helper'
            - '%oro_attachment.attachments_dir%'
    # Email template API
    d_wietor_pmanager.pdftemplate.api:
        class: %d_wietor_pmanager.pdftemplate.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %d_wietor_pmanager.pdftemplate.entity.class%
            - @doctrine.orm.entity_manager
    d_wietor_pmanager.pdftemplate.datagrid_helper:
        class: %d_wietor_pmanager.pdftemplate.datagrid_helper.class%
        arguments:
            - @oro_entity.entity_provider
            - @translator
    d_wietor_pmanager.pdftemplate.datagrid_view_list:
        class: %d_wietor_pmanager.pdftemplate.datagrid_view_list.class%
        arguments:
            - @translator
    d_wietor_pmanager.tcpdf:
        class: %d_wietor_pmanager.tcpdf.class%
        file: %d_wietor_pmanager.file%
        arguments:
            - %d_wietor_pmanager.class%
        tags:
            - { name: pmanager.tcpdf, alias: pmanager_tcpdf }

    d_wietor_pmanager.cache:
          parent: oro.cache.abstract
          calls:
              - [setNamespace, ['d_wietor_pmanager.cache']]
    # email template twig instance
    # Available variables services
    d_wietor_pmanager.listener.config_listener:
        class: DWietor\Bundle\PmanagerBundle\EventListener\EntityConfigListener
        arguments:
            - @d_wietor_pmanager.cache
            - %d_wietor_pmanager.cache.available_in_template_key%
        tags:
            - { name: kernel.event_listener, event: oro.entity_config.pre_flush, method: preFlush }
    d_wietor_pmanager.twig.string_loader:
        class: Twig_Loader_String
    d_wietor_pmanager.pdftemplate_renderer:
        class: %d_wietor_pmanager.pdftemplate_renderer.class%
        arguments:
            - @d_wietor_pmanager.twig.string_loader
            -  # twig environment options
              strict_variables: true
            - @d_wietor_pmanager.pdftemplate.variable_provider
            - @d_wietor_pmanager.cache
            - %d_wietor_pmanager.cache.available_in_template_key%
            - @d_wietor_pmanager.twig.pdftemplate_sandbox
            - @translator
            - @oro_locale.settings
            - @doctrine
        lazy: true
    d_wietor_pmanager.producttemplate_renderer:
        class: %d_wietor_pmanager.producttemplate_renderer.class%
        arguments:
            - @d_wietor_pmanager.twig.string_loader
            -  # twig environment options
              strict_variables: true
            - @d_wietor_pmanager.pdftemplate.variable_provider
            - @d_wietor_pmanager.cache
            - %d_wietor_pmanager.cache.available_in_template_key%
            - @d_wietor_pmanager.twig.pdftemplate_sandbox
            - @translator
            - @oro_locale.settings
            - @doctrine
        lazy: true
    d_wietor_pmanager.publication_renderer:
        class: %d_wietor_pmanager.publication_renderer.class%
        arguments:
            - @d_wietor_pmanager.twig.string_loader
            -  # twig environment options
              strict_variables: true
            - @d_wietor_pmanager.pdftemplate.variable_provider
            - @d_wietor_pmanager.cache
            - %d_wietor_pmanager.cache.available_in_template_key%
            - @d_wietor_pmanager.twig.pdftemplate_sandbox
            - @translator
            - @oro_locale.settings
            - @doctrine
        lazy: true
    d_wietor_pmanager.twig.pdftemplate_sandbox:
        class: Twig_Extension_Sandbox
        arguments:
            - @d_wietor_pmanager.twig.security_policy
            - true # use sandbox globally in instance
    d_wietor_pmanager.pdftemplate.variable_provider:
        class: %d_wietor_pmanager.pdftemplate.variable_provider.class%

    d_wietor_pmanager.pdftemplate.variable_provider.entity:
        class: %d_wietor_pmanager.pdftemplate.variable_provider.entity.class%
        arguments:
            - @translator
            - @oro_entity_config.config_manager
            - @doctrine
            - @oro_ui.formatter
        lazy: true
        public: false
        tags:
            - { name: d_wietor_pmanager.pdftemplate.variable_provider, scope: entity }
    d_wietor_pmanager.twig.security_policy:
        class: %oro_email.twig.email_security_policy.class%
        arguments:
            # tags
            - [ 'app', 'for', 'if', 'spaceless' ]
            # filters
            - [ 'default', 'date', 'escape', 'format', 'length', 'lower', 'nl2br', 'number_format', 'title', 'trim', 'upper' ,'oro_format_currency' ]
            # methods
            - []
            # properties
            - []
            # functions
            - [ 'date' ]
    d_wietor_pmanager.pdftemplate.variable_provider.system:
        class: %d_wietor_pmanager.pdftemplate.variable_provider.system.class%
        lazy: true
        arguments:
            - @translator
            - @oro_config.user
            - @oro_locale.formatter.date_time
        lazy: true
        public: false
        tags:
            - { name: d_wietor_pmanager.pdftemplate.variable_provider, scope: system }

    d_wietor_pmanager.pdftemplate.variable_provider.user:
        class: %d_wietor_pmanager.pdftemplate.variable_provider.user.class%
        lazy: true
        arguments:
            - @translator
            - @oro_security.security_facade
            - @oro_entity.entity_name_resolver
            - @oro_config.user
        lazy: true
        public: false
        tags:
            - { name: d_wietor_pmanager.pdftemplate.variable_provider, scope: system }
    d_wietor_pmanager.validator.pdf_template_syntax:
        class: DWietor\Bundle\PmanagerBundle\Validator\PDFTemplateSyntaxValidator
        arguments:
            - @d_wietor_pmanager.pdftemplate_renderer
            - @oro_locale.settings
            - @oro_config.user
            - @oro_entity_config.provider.entity
            - @translator
        tags:
            - { name: validator.constraint_validator, alias: d_wietor_pmanager.pdftemplate_syntax_validator }
            
    d_wietor_pmanager.pdftemplate.owner.provider.storage:
        public: false
        class: %d_wietor_pmanager.pdftemplate.owner.provider.storage.class%
    d_wietor_pmanager.pdftemplate.form.autocomplete.getpdf.search_handler:
        parent: oro_form.autocomplete.search_handler
        arguments:
            - %d_wietor_pmanager.pdftemplate.entity.class%
            - ["name"]
        tags:
            - { name: oro_form.autocomplete.search_handler, alias: PDFtemplates, acl_resource: pmanager_defaut_view }
    d_wietor_pmanager.widget_provider.actions:
        parent: oro_ui.widget_provider.action_button.abstract
        arguments:
            - d_wietor_pmanager_add_button
            - d_wietor_pmanager_add_link
        tags:
            - { name: oro_ui.view_action_provider, group: activity, priority: 100 }
            - { name: oro_ui.update_action_provider, group: activity, priority: 100 }
    d_wietor_pmanager.placeholder.filter:
        class: %d_wietor_pmanager.placeholder.filter.class%
        arguments:
            - @d_wietor_pmanager.provider.configuration
            - @oro_entity.doctrine_helper
    d_wietor_pmanager.form.autocomplete.type.update.pdftemplate_handler:
        public: false
        parent: oro_form.autocomplete.search_handler
        arguments:
            - '%d_wietor_pmanager.pdftemplate.entity.class%'
            - ["name"]
        tags:
            - { name: oro_form.autocomplete.search_handler, alias: pmanager_template_autocomplete, acl_resource: pmanager_template_index }
